import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { SpriteInjector } from "@/components/ui/IconSprite";
import SmoothScrolling from "@/components/SmoothScrolling";
import { PopupProvider } from "@/app/context/PopupContext";
import PopupForm from "@/components/PopupForm";


const plusJakarta = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
  display: "swap",
});



export const metadata: Metadata = {
  title: "Refyne",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${plusJakarta.variable}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <SpriteInjector />
        <SmoothScrolling>
          <PopupProvider>
            <Header />
            {children}
            <Footer />
            <PopupForm />
          </PopupProvider>
        </SmoothScrolling>
      </body>
    </html>
  );
}
